global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/prometheus-alerts.yml

scrape_configs:
  - job_name: ambonmud
    static_configs:
      - targets: [host.docker.internal:8080]
    metrics_path: /metrics
